### ISSUE TITLE
Could you please push the source code?

### ISSUE THREAD

**Issue by MCredbear** [penglezos/raphael#1]
I want to port sailfiskOS to K20Pro,could you give me some help?

**Comment by penglezos** [comment]
Hey @MCredbear device and vendor trees are already uploaded on my github profile. I won't help you in porting to another device tho.

Have a nice day and stay safe.

**Comment by MCredbear** [comment]
> Hey @MCredbear device and vendor trees are already uploaded on my github profile. I won't help you in porting to another device tho.
> 
> Have a nice day and stay safe.

Thanks,
but could you also push the code when it was lineage17?

**Comment by penglezos** [comment]
> > Hey @MCredbear device and vendor trees are already uploaded on my github profile. I won't help you in porting to another device tho.
> > Have a nice day and stay safe.
> 
> Thanks,
> but could you also push the code when it was lineage17?

It's already pushed check the source.
